// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    AddUpdateLlmConfigApiV1AdminSettingsLlmsPostData,
    AddUpdateLlmConfigApiV1AdminSettingsLlmsPostErrors,
    AddUpdateLlmConfigApiV1AdminSettingsLlmsPostResponses,
    AdminLoginApiV1AdminLoginPostData,
    AdminLoginApiV1AdminLoginPostErrors,
    AdminLoginApiV1AdminLoginPostResponses,
    AdminLogoutApiV1AdminLogoutPostData,
    AdminLogoutApiV1AdminLogoutPostErrors,
    AdminLogoutApiV1AdminLogoutPostResponses,
    AdminMeApiV1AdminMeGetData,
    AdminMeApiV1AdminMeGetErrors,
    AdminMeApiV1AdminMeGetResponses,
    AdminRefreshApiV1AdminRefreshPostData,
    AdminRefreshApiV1AdminRefreshPostErrors,
    AdminRefreshApiV1AdminRefreshPostResponses,
    CreateBotApiV1BotsPostData,
    CreateBotApiV1BotsPostErrors,
    CreateBotApiV1BotsPostResponses,
    CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostData,
    CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostErrors,
    CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostResponses,
    CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostData,
    CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostErrors,
    CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostResponses,
    CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchData,
    CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchErrors,
    CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponses,
    DeleteBotApiV1BotsBotIdDeleteData,
    DeleteBotApiV1BotsBotIdDeleteErrors,
    DeleteBotApiV1BotsBotIdDeleteResponses,
    DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteData,
    DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteErrors,
    DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteResponses,
    DeleteLlmConfigApiV1AdminSettingsLlmsModelNameDeleteData,
    DeleteLlmConfigApiV1AdminSettingsLlmsModelNameDeleteErrors,
    DeleteLlmConfigApiV1AdminSettingsLlmsModelNameDeleteResponses,
    GetAccessTokenApiV1AuthTokenSessionIdGetData,
    GetAccessTokenApiV1AuthTokenSessionIdGetErrors,
    GetAccessTokenApiV1AuthTokenSessionIdGetResponses,
    GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetData,
    GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetErrors,
    GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponses,
    GetAvailableLlmsApiV1ConfigAvailableLlmsGetData,
    GetAvailableLlmsApiV1ConfigAvailableLlmsGetErrors,
    GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponses,
    GetBotApiV1BotsBotIdGetData,
    GetBotApiV1BotsBotIdGetErrors,
    GetBotApiV1BotsBotIdGetResponses,
    GetBotStatusApiV1BotsBotIdStatusGetData,
    GetBotStatusApiV1BotsBotIdStatusGetErrors,
    GetBotStatusApiV1BotsBotIdStatusGetResponses,
    GetConfigsApiV1ConfigGetData,
    GetConfigsApiV1ConfigGetErrors,
    GetConfigsApiV1ConfigGetResponses,
    GetCurrentUserInfoApiV1AuthMeGetData,
    GetCurrentUserInfoApiV1AuthMeGetErrors,
    GetCurrentUserInfoApiV1AuthMeGetResponses,
    GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetData,
    GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetErrors,
    GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetResponses,
    GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetData,
    GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetErrors,
    GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetResponses,
    GetGitlabSettingsApiV1AdminSettingsGitlabGetData,
    GetGitlabSettingsApiV1AdminSettingsGitlabGetErrors,
    GetGitlabSettingsApiV1AdminSettingsGitlabGetResponses,
    GetGitlabUserinfoApiV1GitlabUserinfoGetData,
    GetGitlabUserinfoApiV1GitlabUserinfoGetErrors,
    GetGitlabUserinfoApiV1GitlabUserinfoGetResponses,
    GitlabAuthApiV1AuthGitlabCallbackGetData,
    GitlabAuthApiV1AuthGitlabCallbackGetErrors,
    GitlabAuthApiV1AuthGitlabCallbackGetResponses,
    GitlabLoginApiV1AuthGitlabLoginGetData,
    GitlabLoginApiV1AuthGitlabLoginGetErrors,
    GitlabLoginApiV1AuthGitlabLoginGetResponses,
    ListBotsApiV1BotsGetData,
    ListBotsApiV1BotsGetErrors,
    ListBotsApiV1BotsGetResponses,
    ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetData,
    ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetErrors,
    ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetResponses,
    ListGitlabProjectsApiV1GitlabProjectsGetData,
    ListGitlabProjectsApiV1GitlabProjectsGetErrors,
    ListGitlabProjectsApiV1GitlabProjectsGetResponses,
    ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetData,
    ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetErrors,
    ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetResponses,
    ListLlmConfigsApiV1AdminSettingsLlmsGetData,
    ListLlmConfigsApiV1AdminSettingsLlmsGetErrors,
    ListLlmConfigsApiV1AdminSettingsLlmsGetResponses,
    LogoutApiV1AuthLogoutPostData,
    LogoutApiV1AuthLogoutPostErrors,
    LogoutApiV1AuthLogoutPostResponses,
    PatchGitlabSettingsApiV1AdminSettingsGitlabPatchData,
    PatchGitlabSettingsApiV1AdminSettingsGitlabPatchErrors,
    PatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponses,
    RefreshTokenApiV1AuthRefreshPostData,
    RefreshTokenApiV1AuthRefreshPostErrors,
    RefreshTokenApiV1AuthRefreshPostResponses,
    RevokeBotTokenApiV1BotsBotIdRevokeDeleteData,
    RevokeBotTokenApiV1BotsBotIdRevokeDeleteErrors,
    RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponses,
    RotateBotTokenApiV1BotsBotIdRotateTokenPatchData,
    RotateBotTokenApiV1BotsBotIdRotateTokenPatchErrors,
    RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponses,
    ToggleBotActiveApiV1BotsBotIdToggleActivePatchData,
    ToggleBotActiveApiV1BotsBotIdToggleActivePatchErrors,
    ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponses,
    UpdateBotApiV1BotsBotIdPatchData,
    UpdateBotApiV1BotsBotIdPatchErrors,
    UpdateBotApiV1BotsBotIdPatchResponses,
    UpdateConfigsApiV1ConfigPatchData,
    UpdateConfigsApiV1ConfigPatchErrors,
    UpdateConfigsApiV1ConfigPatchResponses,
    WebhookApiV1WebhooksBotUserIdPostData,
    WebhookApiV1WebhooksBotUserIdPostErrors,
    WebhookApiV1WebhooksBotUserIdPostResponses,
} from "./types.gen";
import {
    zAddUpdateLlmConfigApiV1AdminSettingsLlmsPostData,
    zAddUpdateLlmConfigApiV1AdminSettingsLlmsPostResponse,
    zAdminLoginApiV1AdminLoginPostData,
    zAdminLoginApiV1AdminLoginPostResponse,
    zAdminLogoutApiV1AdminLogoutPostData,
    zAdminMeApiV1AdminMeGetData,
    zAdminMeApiV1AdminMeGetResponse,
    zAdminRefreshApiV1AdminRefreshPostData,
    zAdminRefreshApiV1AdminRefreshPostResponse,
    zCreateBotApiV1BotsPostData,
    zCreateBotApiV1BotsPostResponse,
    zCreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostData,
    zCreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostData,
    zCreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchData,
    zCreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponse,
    zDeleteBotApiV1BotsBotIdDeleteData,
    zDeleteBotApiV1BotsBotIdDeleteResponse,
    zDeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteData,
    zDeleteLlmConfigApiV1AdminSettingsLlmsModelNameDeleteData,
    zGetAccessTokenApiV1AuthTokenSessionIdGetData,
    zGetAccessTokenApiV1AuthTokenSessionIdGetResponse,
    zGetAvailableAvatarsApiV1ConfigAvailableAvatarsGetData,
    zGetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponse,
    zGetAvailableLlmsApiV1ConfigAvailableLlmsGetData,
    zGetAvailableLlmsApiV1ConfigAvailableLlmsGetResponse,
    zGetBotApiV1BotsBotIdGetData,
    zGetBotApiV1BotsBotIdGetResponse,
    zGetBotStatusApiV1BotsBotIdStatusGetData,
    zGetBotStatusApiV1BotsBotIdStatusGetResponse,
    zGetConfigsApiV1ConfigGetData,
    zGetConfigsApiV1ConfigGetResponse,
    zGetCurrentUserInfoApiV1AuthMeGetData,
    zGetCurrentUserInfoApiV1AuthMeGetResponse,
    zGetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetData,
    zGetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetData,
    zGetGitlabSettingsApiV1AdminSettingsGitlabGetData,
    zGetGitlabSettingsApiV1AdminSettingsGitlabGetResponse,
    zGetGitlabUserinfoApiV1GitlabUserinfoGetData,
    zGetGitlabUserinfoApiV1GitlabUserinfoGetResponse,
    zGitlabAuthApiV1AuthGitlabCallbackGetData,
    zGitlabLoginApiV1AuthGitlabLoginGetData,
    zGitlabLoginApiV1AuthGitlabLoginGetResponse,
    zListBotsApiV1BotsGetData,
    zListBotsApiV1BotsGetResponse,
    zListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetData,
    zListGitlabProjectsApiV1GitlabProjectsGetData,
    zListGitlabProjectsApiV1GitlabProjectsGetResponse,
    zListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetData,
    zListLlmConfigsApiV1AdminSettingsLlmsGetData,
    zListLlmConfigsApiV1AdminSettingsLlmsGetResponse,
    zLogoutApiV1AuthLogoutPostData,
    zPatchGitlabSettingsApiV1AdminSettingsGitlabPatchData,
    zPatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponse,
    zRefreshTokenApiV1AuthRefreshPostData,
    zRefreshTokenApiV1AuthRefreshPostResponse,
    zRevokeBotTokenApiV1BotsBotIdRevokeDeleteData,
    zRevokeBotTokenApiV1BotsBotIdRevokeDeleteResponse,
    zRotateBotTokenApiV1BotsBotIdRotateTokenPatchData,
    zRotateBotTokenApiV1BotsBotIdRotateTokenPatchResponse,
    zToggleBotActiveApiV1BotsBotIdToggleActivePatchData,
    zToggleBotActiveApiV1BotsBotIdToggleActivePatchResponse,
    zUpdateBotApiV1BotsBotIdPatchData,
    zUpdateBotApiV1BotsBotIdPatchResponse,
    zUpdateConfigsApiV1ConfigPatchData,
    zUpdateConfigsApiV1ConfigPatchResponse,
    zWebhookApiV1WebhooksBotUserIdPostData,
} from "./zod.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Refresh Token
 *
 * Refresh access and refresh tokens using a valid refresh token.
 */
export const refreshTokenApiV1AuthRefreshPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<RefreshTokenApiV1AuthRefreshPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        RefreshTokenApiV1AuthRefreshPostResponses,
        RefreshTokenApiV1AuthRefreshPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zRefreshTokenApiV1AuthRefreshPostData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zRefreshTokenApiV1AuthRefreshPostResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/auth/refresh",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Logout
 *
 * Log out the currently authenticated user.
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(
    options: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        LogoutApiV1AuthLogoutPostResponses,
        LogoutApiV1AuthLogoutPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zLogoutApiV1AuthLogoutPostData.parseAsync(data);
        },
        url: "/api/v1/auth/logout",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Get Current User Info
 *
 * Get information about the currently authenticated user.
 */
export const getCurrentUserInfoApiV1AuthMeGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetCurrentUserInfoApiV1AuthMeGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetCurrentUserInfoApiV1AuthMeGetResponses,
        GetCurrentUserInfoApiV1AuthMeGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetCurrentUserInfoApiV1AuthMeGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetCurrentUserInfoApiV1AuthMeGetResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/auth/me",
        ...options,
    });
};

/**
 * Gitlab Login
 *
 * Redirect to GitLab for authentication.
 */
export const gitlabLoginApiV1AuthGitlabLoginGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GitlabLoginApiV1AuthGitlabLoginGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GitlabLoginApiV1AuthGitlabLoginGetResponses,
        GitlabLoginApiV1AuthGitlabLoginGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGitlabLoginApiV1AuthGitlabLoginGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGitlabLoginApiV1AuthGitlabLoginGetResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/auth/gitlab/login",
        ...options,
    });
};

/**
 * Gitlab Auth
 *
 * Handle the callback from GitLab after user authentication.
 */
export const gitlabAuthApiV1AuthGitlabCallbackGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GitlabAuthApiV1AuthGitlabCallbackGetData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GitlabAuthApiV1AuthGitlabCallbackGetResponses,
        GitlabAuthApiV1AuthGitlabCallbackGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGitlabAuthApiV1AuthGitlabCallbackGetData.parseAsync(
                data,
            );
        },
        url: "/api/v1/auth/gitlab/callback",
        ...options,
    });
};

/**
 * Get Access Token
 *
 * Fetch access and refresh tokens using session ID.
 */
export const getAccessTokenApiV1AuthTokenSessionIdGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetAccessTokenApiV1AuthTokenSessionIdGetData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).get<
        GetAccessTokenApiV1AuthTokenSessionIdGetResponses,
        GetAccessTokenApiV1AuthTokenSessionIdGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetAccessTokenApiV1AuthTokenSessionIdGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGetAccessTokenApiV1AuthTokenSessionIdGetResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/auth/token/{session_id}",
        ...options,
    });
};

/**
 * Admin Login
 *
 * Authenticate an admin with username + password.
 */
export const adminLoginApiV1AdminLoginPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<AdminLoginApiV1AdminLoginPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        AdminLoginApiV1AdminLoginPostResponses,
        AdminLoginApiV1AdminLoginPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zAdminLoginApiV1AdminLoginPostData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zAdminLoginApiV1AdminLoginPostResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/admin/login",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Admin Refresh
 *
 * Refresh an admin session, re-minting an admin-scoped access token.
 */
export const adminRefreshApiV1AdminRefreshPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<AdminRefreshApiV1AdminRefreshPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        AdminRefreshApiV1AdminRefreshPostResponses,
        AdminRefreshApiV1AdminRefreshPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zAdminRefreshApiV1AdminRefreshPostData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zAdminRefreshApiV1AdminRefreshPostResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/admin/refresh",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Admin Logout
 *
 * Revoke the admin's refresh session.
 */
export const adminLogoutApiV1AdminLogoutPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<AdminLogoutApiV1AdminLogoutPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        AdminLogoutApiV1AdminLogoutPostResponses,
        AdminLogoutApiV1AdminLogoutPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zAdminLogoutApiV1AdminLogoutPostData.parseAsync(data);
        },
        url: "/api/v1/admin/logout",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Admin Me
 */
export const adminMeApiV1AdminMeGet = <ThrowOnError extends boolean = false>(
    options?: Options<AdminMeApiV1AdminMeGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        AdminMeApiV1AdminMeGetResponses,
        AdminMeApiV1AdminMeGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zAdminMeApiV1AdminMeGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zAdminMeApiV1AdminMeGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/admin/me",
        ...options,
    });
};

/**
 * Get Gitlab Settings
 */
export const getGitlabSettingsApiV1AdminSettingsGitlabGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetGitlabSettingsApiV1AdminSettingsGitlabGetData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? client).get<
        GetGitlabSettingsApiV1AdminSettingsGitlabGetResponses,
        GetGitlabSettingsApiV1AdminSettingsGitlabGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetGitlabSettingsApiV1AdminSettingsGitlabGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGetGitlabSettingsApiV1AdminSettingsGitlabGetResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/admin/settings/gitlab",
        ...options,
    });
};

/**
 * Patch Gitlab Settings
 */
export const patchGitlabSettingsApiV1AdminSettingsGitlabPatch = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        PatchGitlabSettingsApiV1AdminSettingsGitlabPatchData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).patch<
        PatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponses,
        PatchGitlabSettingsApiV1AdminSettingsGitlabPatchErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zPatchGitlabSettingsApiV1AdminSettingsGitlabPatchData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zPatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/admin/settings/gitlab",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * List Llm Configs
 *
 * List the available LLM model configurations (admin).
 */
export const listLlmConfigsApiV1AdminSettingsLlmsGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        ListLlmConfigsApiV1AdminSettingsLlmsGetData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? client).get<
        ListLlmConfigsApiV1AdminSettingsLlmsGetResponses,
        ListLlmConfigsApiV1AdminSettingsLlmsGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zListLlmConfigsApiV1AdminSettingsLlmsGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zListLlmConfigsApiV1AdminSettingsLlmsGetResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/admin/settings/llms",
        ...options,
    });
};

/**
 * Add Update Llm Config
 *
 * Add a new LLM model configuration or update an existing one (admin).
 */
export const addUpdateLlmConfigApiV1AdminSettingsLlmsPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        AddUpdateLlmConfigApiV1AdminSettingsLlmsPostData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).post<
        AddUpdateLlmConfigApiV1AdminSettingsLlmsPostResponses,
        AddUpdateLlmConfigApiV1AdminSettingsLlmsPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zAddUpdateLlmConfigApiV1AdminSettingsLlmsPostData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zAddUpdateLlmConfigApiV1AdminSettingsLlmsPostResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/admin/settings/llms",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Delete Llm Config
 *
 * Delete an LLM model configuration (admin).
 */
export const deleteLlmConfigApiV1AdminSettingsLlmsModelNameDelete = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        DeleteLlmConfigApiV1AdminSettingsLlmsModelNameDeleteData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).delete<
        DeleteLlmConfigApiV1AdminSettingsLlmsModelNameDeleteResponses,
        DeleteLlmConfigApiV1AdminSettingsLlmsModelNameDeleteErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zDeleteLlmConfigApiV1AdminSettingsLlmsModelNameDeleteData.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/admin/settings/llms/{model_name}",
        ...options,
    });
};

/**
 * Get Gitlab Userinfo
 *
 * Get GitLab user information for the authenticated user.
 */
export const getGitlabUserinfoApiV1GitlabUserinfoGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetGitlabUserinfoApiV1GitlabUserinfoGetData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? client).get<
        GetGitlabUserinfoApiV1GitlabUserinfoGetResponses,
        GetGitlabUserinfoApiV1GitlabUserinfoGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetGitlabUserinfoApiV1GitlabUserinfoGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGetGitlabUserinfoApiV1GitlabUserinfoGetResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/gitlab/userinfo",
        ...options,
    });
};

/**
 * List Gitlab Projects
 *
 * list GitLab projects for the authenticated user.
 */
export const listGitlabProjectsApiV1GitlabProjectsGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        ListGitlabProjectsApiV1GitlabProjectsGetData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? client).get<
        ListGitlabProjectsApiV1GitlabProjectsGetResponses,
        ListGitlabProjectsApiV1GitlabProjectsGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zListGitlabProjectsApiV1GitlabProjectsGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zListGitlabProjectsApiV1GitlabProjectsGetResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/gitlab/projects",
        ...options,
    });
};

/**
 * List Gitlab Project Access Tokens
 *
 * List access tokens for a GitLab project.
 */
export const listGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGet =
    <ThrowOnError extends boolean = false>(
        options: Options<
            ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).get<
            ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetResponses,
            ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetData.parseAsync(
                    data,
                );
            },
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/api/v1/gitlab/projects/{project_id}/access-tokens",
            ...options,
        });
    };

/**
 * Create Gitlab Project Access Token
 *
 * Create a new access token for a GitLab project.
 */
export const createGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPost =
    <ThrowOnError extends boolean = false>(
        options: Options<
            CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).post<
            CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostResponses,
            CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zCreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostData.parseAsync(
                    data,
                );
            },
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/api/v1/gitlab/projects/{project_id}/access-tokens",
            ...options,
        });
    };

/**
 * Get Gitlab Project Access Token
 *
 * Get a specific access token for a GitLab project.
 */
export const getGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGet =
    <ThrowOnError extends boolean = false>(
        options: Options<
            GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).get<
            GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetResponses,
            GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zGetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetData.parseAsync(
                    data,
                );
            },
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/api/v1/gitlab/projects/{project_id}/access-tokens/{access_token_id}",
            ...options,
        });
    };

/**
 * List Gitlab Project Webhooks
 *
 * List webhooks for a GitLab project.
 */
export const listGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGet =
    <ThrowOnError extends boolean = false>(
        options: Options<
            ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).get<
            ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetResponses,
            ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetData.parseAsync(
                    data,
                );
            },
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/api/v1/gitlab/projects/{project_id}/webhooks",
            ...options,
        });
    };

/**
 * Create Gitlab Project Webhook
 *
 * Create a new webhook for a GitLab project.
 */
export const createGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPost =
    <ThrowOnError extends boolean = false>(
        options: Options<
            CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).post<
            CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostResponses,
            CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zCreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostData.parseAsync(
                    data,
                );
            },
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/api/v1/gitlab/projects/{project_id}/webhooks",
            ...options,
        });
    };

/**
 * Delete Gitlab Project Webhook
 *
 * Delete a webhook for a GitLab project.
 */
export const deleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDelete =
    <ThrowOnError extends boolean = false>(
        options: Options<
            DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).delete<
            DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteResponses,
            DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zDeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteData.parseAsync(
                    data,
                );
            },
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/api/v1/gitlab/projects/{project_id}/webhooks/{hook_id}",
            ...options,
        });
    };

/**
 * Get Gitlab Project Webhook
 *
 * Get a specific webhook for a GitLab project.
 */
export const getGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGet =
    <ThrowOnError extends boolean = false>(
        options: Options<
            GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).get<
            GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetResponses,
            GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zGetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetData.parseAsync(
                    data,
                );
            },
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/api/v1/gitlab/projects/{project_id}/webhooks/{hook_id}",
            ...options,
        });
    };

/**
 * Get Bot Status
 *
 * Get the status of a bot by its ID.
 */
export const getBotStatusApiV1BotsBotIdStatusGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetBotStatusApiV1BotsBotIdStatusGetData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetBotStatusApiV1BotsBotIdStatusGetResponses,
        GetBotStatusApiV1BotsBotIdStatusGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetBotStatusApiV1BotsBotIdStatusGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGetBotStatusApiV1BotsBotIdStatusGetResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/{bot_id}/status",
        ...options,
    });
};

/**
 * List Bots
 *
 * List all bots with pagination.
 */
export const listBotsApiV1BotsGet = <ThrowOnError extends boolean = false>(
    options?: Options<ListBotsApiV1BotsGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        ListBotsApiV1BotsGetResponses,
        ListBotsApiV1BotsGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zListBotsApiV1BotsGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zListBotsApiV1BotsGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/",
        ...options,
    });
};

/**
 * Create Bot
 *
 * Create a new bot for a GitLab project.
 */
export const createBotApiV1BotsPost = <ThrowOnError extends boolean = false>(
    options: Options<CreateBotApiV1BotsPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        CreateBotApiV1BotsPostResponses,
        CreateBotApiV1BotsPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zCreateBotApiV1BotsPostData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zCreateBotApiV1BotsPostResponse.parseAsync(data);
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Delete Bot
 *
 * Delete a bot by its ID.
 */
export const deleteBotApiV1BotsBotIdDelete = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteBotApiV1BotsBotIdDeleteData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<
        DeleteBotApiV1BotsBotIdDeleteResponses,
        DeleteBotApiV1BotsBotIdDeleteErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zDeleteBotApiV1BotsBotIdDeleteData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zDeleteBotApiV1BotsBotIdDeleteResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/{bot_id}",
        ...options,
    });
};

/**
 * Get Bot
 *
 * Get a bot by its ID.
 */
export const getBotApiV1BotsBotIdGet = <ThrowOnError extends boolean = false>(
    options: Options<GetBotApiV1BotsBotIdGetData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetBotApiV1BotsBotIdGetResponses,
        GetBotApiV1BotsBotIdGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetBotApiV1BotsBotIdGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetBotApiV1BotsBotIdGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/{bot_id}",
        ...options,
    });
};

/**
 * Update Bot
 *
 * Update a bot by its ID.
 */
export const updateBotApiV1BotsBotIdPatch = <
    ThrowOnError extends boolean = false,
>(
    options: Options<UpdateBotApiV1BotsBotIdPatchData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<
        UpdateBotApiV1BotsBotIdPatchResponses,
        UpdateBotApiV1BotsBotIdPatchErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zUpdateBotApiV1BotsBotIdPatchData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zUpdateBotApiV1BotsBotIdPatchResponse.parseAsync(data);
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/{bot_id}",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Create New Bot Access Token
 *
 * Create a new access token for a bot by its ID and revoke the old one.
 */
export const createNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatch = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).patch<
        CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponses,
        CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zCreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zCreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/{bot_id}/new-access-token",
        ...options,
    });
};

/**
 * Toggle Bot Active
 *
 * Toggle a bot's active status by its ID.
 */
export const toggleBotActiveApiV1BotsBotIdToggleActivePatch = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        ToggleBotActiveApiV1BotsBotIdToggleActivePatchData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).patch<
        ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponses,
        ToggleBotActiveApiV1BotsBotIdToggleActivePatchErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zToggleBotActiveApiV1BotsBotIdToggleActivePatchData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zToggleBotActiveApiV1BotsBotIdToggleActivePatchResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/{bot_id}/toggle-active",
        ...options,
    });
};

/**
 * Revoke Bot Token
 *
 * Revoke a bot's GitLab project access token.
 */
export const revokeBotTokenApiV1BotsBotIdRevokeDelete = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        RevokeBotTokenApiV1BotsBotIdRevokeDeleteData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).delete<
        RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponses,
        RevokeBotTokenApiV1BotsBotIdRevokeDeleteErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zRevokeBotTokenApiV1BotsBotIdRevokeDeleteData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zRevokeBotTokenApiV1BotsBotIdRevokeDeleteResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/{bot_id}/revoke",
        ...options,
    });
};

/**
 * Rotate Bot Token
 *
 * Rotate a bot's GitLab project access token.
 */
export const rotateBotTokenApiV1BotsBotIdRotateTokenPatch = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        RotateBotTokenApiV1BotsBotIdRotateTokenPatchData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).patch<
        RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponses,
        RotateBotTokenApiV1BotsBotIdRotateTokenPatchErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zRotateBotTokenApiV1BotsBotIdRotateTokenPatchData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zRotateBotTokenApiV1BotsBotIdRotateTokenPatchResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/bots/{bot_id}/rotate-token",
        ...options,
    });
};

/**
 * Get Available Avatars
 *
 * Get a list of available bot avatars.
 */
export const getAvailableAvatarsApiV1ConfigAvailableAvatarsGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? client).get<
        GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponses,
        GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetAvailableAvatarsApiV1ConfigAvailableAvatarsGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/config/available-avatars",
        ...options,
    });
};

/**
 * Get Available Llms
 *
 * Get a list of available LLM models.
 */
export const getAvailableLlmsApiV1ConfigAvailableLlmsGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetAvailableLlmsApiV1ConfigAvailableLlmsGetData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? client).get<
        GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponses,
        GetAvailableLlmsApiV1ConfigAvailableLlmsGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetAvailableLlmsApiV1ConfigAvailableLlmsGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGetAvailableLlmsApiV1ConfigAvailableLlmsGetResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/config/available-llms",
        ...options,
    });
};

/**
 * Get Configs
 *
 * Get the current configuration settings.
 */
export const getConfigsApiV1ConfigGet = <ThrowOnError extends boolean = false>(
    options?: Options<GetConfigsApiV1ConfigGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetConfigsApiV1ConfigGetResponses,
        GetConfigsApiV1ConfigGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetConfigsApiV1ConfigGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetConfigsApiV1ConfigGetResponse.parseAsync(data);
        },
        url: "/api/v1/config/",
        ...options,
    });
};

/**
 * Update Configs
 *
 * Update the configuration settings.
 */
export const updateConfigsApiV1ConfigPatch = <
    ThrowOnError extends boolean = false,
>(
    options: Options<UpdateConfigsApiV1ConfigPatchData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<
        UpdateConfigsApiV1ConfigPatchResponses,
        UpdateConfigsApiV1ConfigPatchErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zUpdateConfigsApiV1ConfigPatchData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zUpdateConfigsApiV1ConfigPatchResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/config/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Webhook
 */
export const webhookApiV1WebhooksBotUserIdPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<WebhookApiV1WebhooksBotUserIdPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        WebhookApiV1WebhooksBotUserIdPostResponses,
        WebhookApiV1WebhooksBotUserIdPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zWebhookApiV1WebhooksBotUserIdPostData.parseAsync(
                data,
            );
        },
        url: "/api/v1/webhooks/{bot_user_id}",
        ...options,
    });
};
