// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    GetAccessTokenApiV1AuthTokenSessionIdGetData,
    GetAccessTokenApiV1AuthTokenSessionIdGetErrors,
    GetAccessTokenApiV1AuthTokenSessionIdGetResponses,
    GetCurrentUserInfoApiV1AuthMeGetData,
    GetCurrentUserInfoApiV1AuthMeGetResponses,
    GetGitlabProjectsApiV1GitlabProjectsGetData,
    GetGitlabProjectsApiV1GitlabProjectsGetResponses,
    GetGitlabUserinfoApiV1GitlabUserinfoGetData,
    GetGitlabUserinfoApiV1GitlabUserinfoGetResponses,
    GitlabAuthApiV1AuthGitlabCallbackGetData,
    GitlabAuthApiV1AuthGitlabCallbackGetErrors,
    GitlabAuthApiV1AuthGitlabCallbackGetResponses,
    GitlabLoginApiV1AuthGitlabLoginGetData,
    GitlabLoginApiV1AuthGitlabLoginGetResponses,
    LogoutApiV1AuthLogoutPostData,
    LogoutApiV1AuthLogoutPostErrors,
    LogoutApiV1AuthLogoutPostResponses,
    RefreshTokenApiV1AuthRefreshPostData,
    RefreshTokenApiV1AuthRefreshPostErrors,
    RefreshTokenApiV1AuthRefreshPostResponses,
} from "./types.gen";
import {
    zGetAccessTokenApiV1AuthTokenSessionIdGetData,
    zGetAccessTokenApiV1AuthTokenSessionIdGetResponse,
    zGetCurrentUserInfoApiV1AuthMeGetData,
    zGetCurrentUserInfoApiV1AuthMeGetResponse,
    zGetGitlabProjectsApiV1GitlabProjectsGetData,
    zGetGitlabUserinfoApiV1GitlabUserinfoGetData,
    zGitlabAuthApiV1AuthGitlabCallbackGetData,
    zGitlabLoginApiV1AuthGitlabLoginGetData,
    zGitlabLoginApiV1AuthGitlabLoginGetResponse,
    zLogoutApiV1AuthLogoutPostData,
    zRefreshTokenApiV1AuthRefreshPostData,
    zRefreshTokenApiV1AuthRefreshPostResponse,
} from "./zod.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Refresh Token
 *
 * Refresh access and refresh tokens using a valid refresh token.
 */
export const refreshTokenApiV1AuthRefreshPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<RefreshTokenApiV1AuthRefreshPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        RefreshTokenApiV1AuthRefreshPostResponses,
        RefreshTokenApiV1AuthRefreshPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zRefreshTokenApiV1AuthRefreshPostData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zRefreshTokenApiV1AuthRefreshPostResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/auth/refresh",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Logout
 *
 * Log out the currently authenticated user.
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(
    options: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        LogoutApiV1AuthLogoutPostResponses,
        LogoutApiV1AuthLogoutPostErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zLogoutApiV1AuthLogoutPostData.parseAsync(data);
        },
        url: "/api/v1/auth/logout",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Get Current User Info
 *
 * Get information about the currently authenticated user.
 */
export const getCurrentUserInfoApiV1AuthMeGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GetCurrentUserInfoApiV1AuthMeGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetCurrentUserInfoApiV1AuthMeGetResponses,
        unknown,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetCurrentUserInfoApiV1AuthMeGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetCurrentUserInfoApiV1AuthMeGetResponse.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/auth/me",
        ...options,
    });
};

/**
 * Gitlab Login
 *
 * Redirect to GitLab for authentication.
 */
export const gitlabLoginApiV1AuthGitlabLoginGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<GitlabLoginApiV1AuthGitlabLoginGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GitlabLoginApiV1AuthGitlabLoginGetResponses,
        unknown,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGitlabLoginApiV1AuthGitlabLoginGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGitlabLoginApiV1AuthGitlabLoginGetResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/auth/gitlab/login",
        ...options,
    });
};

/**
 * Gitlab Auth
 *
 * Handle the callback from GitLab after user authentication.
 */
export const gitlabAuthApiV1AuthGitlabCallbackGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GitlabAuthApiV1AuthGitlabCallbackGetData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GitlabAuthApiV1AuthGitlabCallbackGetResponses,
        GitlabAuthApiV1AuthGitlabCallbackGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGitlabAuthApiV1AuthGitlabCallbackGetData.parseAsync(
                data,
            );
        },
        url: "/api/v1/auth/gitlab/callback",
        ...options,
    });
};

/**
 * Get Access Token
 *
 * Fetch access and refresh tokens using session ID.
 */
export const getAccessTokenApiV1AuthTokenSessionIdGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetAccessTokenApiV1AuthTokenSessionIdGetData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).get<
        GetAccessTokenApiV1AuthTokenSessionIdGetResponses,
        GetAccessTokenApiV1AuthTokenSessionIdGetErrors,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetAccessTokenApiV1AuthTokenSessionIdGetData.parseAsync(
                data,
            );
        },
        responseValidator: async (data) => {
            return await zGetAccessTokenApiV1AuthTokenSessionIdGetResponse.parseAsync(
                data,
            );
        },
        url: "/api/v1/auth/token/{session_id}",
        ...options,
    });
};

/**
 * Get Gitlab Userinfo
 *
 * Get GitLab user information for the authenticated user.
 */
export const getGitlabUserinfoApiV1GitlabUserinfoGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetGitlabUserinfoApiV1GitlabUserinfoGetData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? client).get<
        GetGitlabUserinfoApiV1GitlabUserinfoGetResponses,
        unknown,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetGitlabUserinfoApiV1GitlabUserinfoGetData.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/gitlab/userinfo",
        ...options,
    });
};

/**
 * Get Gitlab Projects
 *
 * Get GitLab projects for the authenticated user.
 */
export const getGitlabProjectsApiV1GitlabProjectsGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<
        GetGitlabProjectsApiV1GitlabProjectsGetData,
        ThrowOnError
    >,
) => {
    return (options?.client ?? client).get<
        GetGitlabProjectsApiV1GitlabProjectsGetResponses,
        unknown,
        ThrowOnError
    >({
        requestValidator: async (data) => {
            return await zGetGitlabProjectsApiV1GitlabProjectsGetData.parseAsync(
                data,
            );
        },
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/api/v1/gitlab/projects",
        ...options,
    });
};
