// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AvailableLlm
 */
export type AvailableLlm = {
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Llm Max Output Tokens
     */
    llm_max_output_tokens: number;
    /**
     * Llm Temperature
     */
    llm_temperature: number;
    /**
     * Llm Additional Kwargs
     */
    llm_additional_kwargs?: {
        [key: string]: unknown;
    } | null;
};

/**
 * BotCreate
 */
export type BotCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Gitlab Project Path
     */
    gitlab_project_path: string;
};

/**
 * BotCreateResponse
 */
export type BotCreateResponse = {
    bot: BotRead;
    /**
     * Warning
     */
    warning?: string | null;
};

/**
 * BotDeleteResponse
 */
export type BotDeleteResponse = {
    /**
     * Warning
     */
    warning?: string | null;
};

/**
 * BotRead
 */
export type BotRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Gitlab Project Path
     */
    gitlab_project_path: string;
    /**
     * Gitlab Access Token Id
     */
    gitlab_access_token_id?: number | null;
    /**
     * Gitlab User Id
     */
    gitlab_user_id?: number | null;
    /**
     * Gitlab User Name
     */
    gitlab_user_name?: string | null;
    /**
     * Gitlab Webhook Id
     */
    gitlab_webhook_id?: number | null;
    /**
     * Gitlab Webhook Secret
     */
    gitlab_webhook_secret?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Llm Max Output Tokens
     */
    llm_max_output_tokens: number;
    /**
     * Llm Temperature
     */
    llm_temperature: number;
    /**
     * Llm System Prompt
     */
    llm_system_prompt?: string | null;
    /**
     * Llm Additional Kwargs
     */
    llm_additional_kwargs?: {
        [key: string]: unknown;
    } | null;
};

/**
 * BotReadList
 */
export type BotReadList = {
    /**
     * Total
     */
    total: number;
    /**
     * Items
     */
    items: Array<BotRead>;
};

/**
 * BotStatusResponse
 */
export type BotStatusResponse = {
    /**
     * Status
     */
    status: "ACTIVE" | "STOPPED" | "ERROR";
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * BotStatusToggleResponse
 */
export type BotStatusToggleResponse = {
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * BotUpdate
 */
export type BotUpdate = {
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm Max Output Tokens
     */
    llm_max_output_tokens?: number | null;
    /**
     * Llm Temperature
     */
    llm_temperature?: number | null;
    /**
     * Llm System Prompt
     */
    llm_system_prompt?: string | null;
    /**
     * Llm Additional Kwargs
     */
    llm_additional_kwargs?: {
        [key: string]: unknown;
    } | null;
};

/**
 * BotUpdateResponse
 */
export type BotUpdateResponse = {
    bot: BotRead;
    /**
     * Warning
     */
    warning?: string | null;
};

/**
 * GitlabAuthUrl
 */
export type GitlabAuthUrl = {
    /**
     * Url
     */
    url: string;
};

/**
 * GitlabProject
 */
export type GitlabProject = {
    /**
     * Id
     */
    id: number;
    /**
     * Name With Namespace
     */
    name_with_namespace: string;
    /**
     * Path With Namespace
     */
    path_with_namespace: string;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Access Level
     */
    access_level: number;
    /**
     * Bot Id
     */
    bot_id?: number | null;
    /**
     * Bot Name
     */
    bot_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RefreshTokenIn
 */
export type RefreshTokenIn = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RefreshTokenOut
 */
export type RefreshTokenOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Expires In
     */
    expires_in: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * UserInfo
 */
export type AppSchemasAuthUserInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string | null;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
};

/**
 * UserInfo
 */
export type AppSchemasGitlabUserInfo = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Web Url
     */
    web_url: string;
};

export type RefreshTokenApiV1AuthRefreshPostData = {
    body: RefreshTokenIn;
    path?: never;
    query?: never;
    url: "/api/v1/auth/refresh";
};

export type RefreshTokenApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshTokenApiV1AuthRefreshPostError =
    RefreshTokenApiV1AuthRefreshPostErrors[keyof RefreshTokenApiV1AuthRefreshPostErrors];

export type RefreshTokenApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: RefreshTokenOut;
};

export type RefreshTokenApiV1AuthRefreshPostResponse =
    RefreshTokenApiV1AuthRefreshPostResponses[keyof RefreshTokenApiV1AuthRefreshPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body: RefreshTokenIn;
    path?: never;
    query?: never;
    url: "/api/v1/auth/logout";
};

export type LogoutApiV1AuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError =
    LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentUserInfoApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/auth/me";
};

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasAuthUserInfo;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse =
    GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];

export type GitlabLoginApiV1AuthGitlabLoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/auth/gitlab/login";
};

export type GitlabLoginApiV1AuthGitlabLoginGetResponses = {
    /**
     * Successful Response
     */
    200: GitlabAuthUrl;
};

export type GitlabLoginApiV1AuthGitlabLoginGetResponse =
    GitlabLoginApiV1AuthGitlabLoginGetResponses[keyof GitlabLoginApiV1AuthGitlabLoginGetResponses];

export type GitlabAuthApiV1AuthGitlabCallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: "/api/v1/auth/gitlab/callback";
};

export type GitlabAuthApiV1AuthGitlabCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GitlabAuthApiV1AuthGitlabCallbackGetError =
    GitlabAuthApiV1AuthGitlabCallbackGetErrors[keyof GitlabAuthApiV1AuthGitlabCallbackGetErrors];

export type GitlabAuthApiV1AuthGitlabCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAccessTokenApiV1AuthTokenSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: "/api/v1/auth/token/{session_id}";
};

export type GetAccessTokenApiV1AuthTokenSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAccessTokenApiV1AuthTokenSessionIdGetError =
    GetAccessTokenApiV1AuthTokenSessionIdGetErrors[keyof GetAccessTokenApiV1AuthTokenSessionIdGetErrors];

export type GetAccessTokenApiV1AuthTokenSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: RefreshTokenOut;
};

export type GetAccessTokenApiV1AuthTokenSessionIdGetResponse =
    GetAccessTokenApiV1AuthTokenSessionIdGetResponses[keyof GetAccessTokenApiV1AuthTokenSessionIdGetResponses];

export type GetGitlabUserinfoApiV1GitlabUserinfoGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/gitlab/userinfo";
};

export type GetGitlabUserinfoApiV1GitlabUserinfoGetResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasGitlabUserInfo;
};

export type GetGitlabUserinfoApiV1GitlabUserinfoGetResponse =
    GetGitlabUserinfoApiV1GitlabUserinfoGetResponses[keyof GetGitlabUserinfoApiV1GitlabUserinfoGetResponses];

export type ListGitlabProjectsApiV1GitlabProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
        /**
         * Search
         */
        search?: string | null;
    };
    url: "/api/v1/gitlab/projects";
};

export type ListGitlabProjectsApiV1GitlabProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGitlabProjectsApiV1GitlabProjectsGetError =
    ListGitlabProjectsApiV1GitlabProjectsGetErrors[keyof ListGitlabProjectsApiV1GitlabProjectsGetErrors];

export type ListGitlabProjectsApiV1GitlabProjectsGetResponses = {
    /**
     * Response List Gitlab Projects Api V1 Gitlab Projects Get
     *
     * Successful Response
     */
    200: Array<GitlabProject>;
};

export type ListGitlabProjectsApiV1GitlabProjectsGetResponse =
    ListGitlabProjectsApiV1GitlabProjectsGetResponses[keyof ListGitlabProjectsApiV1GitlabProjectsGetResponses];

export type ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             */
            project_id: string | number;
        };
        query?: never;
        url: "/api/v1/gitlab/projects/{project_id}/access-tokens";
    };

export type ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError;
    };

export type ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetError =
    ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetErrors[keyof ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetErrors];

export type ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetResponses =
    {
        /**
         * Successful Response
         */
        200: unknown;
    };

export type CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             */
            project_id: string | number;
        };
        query?: never;
        url: "/api/v1/gitlab/projects/{project_id}/access-tokens";
    };

export type CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError;
    };

export type CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostError =
    CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostErrors[keyof CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostErrors];

export type CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostResponses =
    {
        /**
         * Successful Response
         */
        200: unknown;
    };

export type GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             */
            project_id: string | number;
            /**
             * Access Token Id
             */
            access_token_id: string | number;
        };
        query?: never;
        url: "/api/v1/gitlab/projects/{project_id}/access-tokens/{access_token_id}";
    };

export type GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError;
    };

export type GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetError =
    GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetErrors[keyof GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetErrors];

export type GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetResponses =
    {
        /**
         * Successful Response
         */
        200: unknown;
    };

export type ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             */
            project_id: string | number;
        };
        query?: never;
        url: "/api/v1/gitlab/projects/{project_id}/webhooks";
    };

export type ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError;
    };

export type ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetError =
    ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetErrors[keyof ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetErrors];

export type ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetResponses =
    {
        /**
         * Successful Response
         */
        200: unknown;
    };

export type CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             */
            project_id: string | number;
        };
        query?: never;
        url: "/api/v1/gitlab/projects/{project_id}/webhooks";
    };

export type CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError;
    };

export type CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostError =
    CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostErrors[keyof CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostErrors];

export type CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostResponses =
    {
        /**
         * Successful Response
         */
        200: unknown;
    };

export type DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             */
            project_id: string | number;
            /**
             * Hook Id
             */
            hook_id: string | number;
        };
        query?: never;
        url: "/api/v1/gitlab/projects/{project_id}/webhooks/{hook_id}";
    };

export type DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError;
    };

export type DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteError =
    DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteErrors[keyof DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteErrors];

export type DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteResponses =
    {
        /**
         * Successful Response
         */
        200: unknown;
    };

export type GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             */
            project_id: string | number;
            /**
             * Hook Id
             */
            hook_id: string | number;
        };
        query?: never;
        url: "/api/v1/gitlab/projects/{project_id}/webhooks/{hook_id}";
    };

export type GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetErrors =
    {
        /**
         * Validation Error
         */
        422: HttpValidationError;
    };

export type GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetError =
    GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetErrors[keyof GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetErrors];

export type GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetResponses =
    {
        /**
         * Successful Response
         */
        200: unknown;
    };

export type GetBotStatusApiV1BotsBotIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: "/api/v1/bots/{bot_id}/status";
};

export type GetBotStatusApiV1BotsBotIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBotStatusApiV1BotsBotIdStatusGetError =
    GetBotStatusApiV1BotsBotIdStatusGetErrors[keyof GetBotStatusApiV1BotsBotIdStatusGetErrors];

export type GetBotStatusApiV1BotsBotIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: BotStatusResponse;
};

export type GetBotStatusApiV1BotsBotIdStatusGetResponse =
    GetBotStatusApiV1BotsBotIdStatusGetResponses[keyof GetBotStatusApiV1BotsBotIdStatusGetResponses];

export type ListBotsApiV1BotsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: "/api/v1/bots/";
};

export type ListBotsApiV1BotsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBotsApiV1BotsGetError =
    ListBotsApiV1BotsGetErrors[keyof ListBotsApiV1BotsGetErrors];

export type ListBotsApiV1BotsGetResponses = {
    /**
     * Successful Response
     */
    200: BotReadList;
};

export type ListBotsApiV1BotsGetResponse =
    ListBotsApiV1BotsGetResponses[keyof ListBotsApiV1BotsGetResponses];

export type CreateBotApiV1BotsPostData = {
    body: BotCreate;
    path?: never;
    query?: never;
    url: "/api/v1/bots/";
};

export type CreateBotApiV1BotsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBotApiV1BotsPostError =
    CreateBotApiV1BotsPostErrors[keyof CreateBotApiV1BotsPostErrors];

export type CreateBotApiV1BotsPostResponses = {
    /**
     * Successful Response
     */
    201: BotCreateResponse;
};

export type CreateBotApiV1BotsPostResponse =
    CreateBotApiV1BotsPostResponses[keyof CreateBotApiV1BotsPostResponses];

export type DeleteBotApiV1BotsBotIdDeleteData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: "/api/v1/bots/{bot_id}";
};

export type DeleteBotApiV1BotsBotIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBotApiV1BotsBotIdDeleteError =
    DeleteBotApiV1BotsBotIdDeleteErrors[keyof DeleteBotApiV1BotsBotIdDeleteErrors];

export type DeleteBotApiV1BotsBotIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: BotDeleteResponse;
};

export type DeleteBotApiV1BotsBotIdDeleteResponse =
    DeleteBotApiV1BotsBotIdDeleteResponses[keyof DeleteBotApiV1BotsBotIdDeleteResponses];

export type UpdateBotApiV1BotsBotIdPatchData = {
    body: BotUpdate;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: "/api/v1/bots/{bot_id}";
};

export type UpdateBotApiV1BotsBotIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBotApiV1BotsBotIdPatchError =
    UpdateBotApiV1BotsBotIdPatchErrors[keyof UpdateBotApiV1BotsBotIdPatchErrors];

export type UpdateBotApiV1BotsBotIdPatchResponses = {
    /**
     * Successful Response
     */
    200: BotUpdateResponse;
};

export type UpdateBotApiV1BotsBotIdPatchResponse =
    UpdateBotApiV1BotsBotIdPatchResponses[keyof UpdateBotApiV1BotsBotIdPatchResponses];

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: "/api/v1/bots/{bot_id}/new-access-token";
};

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchError =
    CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchErrors[keyof CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchErrors];

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponses =
    {
        /**
         * Successful Response
         */
        200: BotUpdateResponse;
    };

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponse =
    CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponses[keyof CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponses];

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: "/api/v1/bots/{bot_id}/toggle-active";
};

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchError =
    ToggleBotActiveApiV1BotsBotIdToggleActivePatchErrors[keyof ToggleBotActiveApiV1BotsBotIdToggleActivePatchErrors];

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponses = {
    /**
     * Successful Response
     */
    200: BotStatusToggleResponse;
};

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponse =
    ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponses[keyof ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponses];

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: "/api/v1/bots/{bot_id}/revoke";
};

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteError =
    RevokeBotTokenApiV1BotsBotIdRevokeDeleteErrors[keyof RevokeBotTokenApiV1BotsBotIdRevokeDeleteErrors];

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponse =
    RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponses[keyof RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponses];

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: "/api/v1/bots/{bot_id}/rotate-token";
};

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchError =
    RotateBotTokenApiV1BotsBotIdRotateTokenPatchErrors[keyof RotateBotTokenApiV1BotsBotIdRotateTokenPatchErrors];

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponses = {
    /**
     * Successful Response
     */
    200: BotRead;
};

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponse =
    RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponses[keyof RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponses];

export type GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/config/available-avatars";
};

export type GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponses = {
    /**
     * Response Get Available Avatars Api V1 Config Available Avatars Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponse =
    GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponses[keyof GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponses];

export type GetAvailableLlmsApiV1ConfigAvailableLlmsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/v1/config/available-llms";
};

export type GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponses = {
    /**
     * Response Get Available Llms Api V1 Config Available Llms Get
     *
     * Successful Response
     */
    200: Array<AvailableLlm>;
};

export type GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponse =
    GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponses[keyof GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponses];
