// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminInfo
 */
export type AdminInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string | null;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
};

/**
 * AdminLoginIn
 */
export type AdminLoginIn = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AdminTokenOut
 */
export type AdminTokenOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Expires In
     */
    expires_in: number;
};

/**
 * BotCreate
 */
export type BotCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Gitlab Project Path
     */
    gitlab_project_path: string;
};

/**
 * BotCreateResponse
 */
export type BotCreateResponse = {
    bot: BotRead;
    /**
     * Warning
     */
    warning?: string | null;
};

/**
 * BotDeleteResponse
 */
export type BotDeleteResponse = {
    /**
     * Warning
     */
    warning?: string | null;
};

/**
 * BotRead
 */
export type BotRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Gitlab Project Path
     */
    gitlab_project_path: string;
    /**
     * Gitlab Access Token Id
     */
    gitlab_access_token_id?: number | null;
    /**
     * Gitlab User Id
     */
    gitlab_user_id?: number | null;
    /**
     * Gitlab User Name
     */
    gitlab_user_name?: string | null;
    /**
     * Gitlab Webhook Id
     */
    gitlab_webhook_id?: number | null;
    /**
     * Gitlab Webhook Secret
     */
    gitlab_webhook_secret?: string | null;
    /**
     * Avatar Name
     */
    avatar_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Llm Max Output Tokens
     */
    llm_max_output_tokens: number;
    /**
     * Llm Temperature
     */
    llm_temperature: number;
    /**
     * Llm System Prompt
     */
    llm_system_prompt?: string | null;
    /**
     * Llm Additional Kwargs
     */
    llm_additional_kwargs?: {
        [key: string]: unknown;
    } | null;
};

/**
 * BotReadList
 */
export type BotReadList = {
    /**
     * Total
     */
    total: number;
    /**
     * Items
     */
    items: Array<BotRead>;
};

/**
 * BotStatusResponse
 */
export type BotStatusResponse = {
    /**
     * Status
     */
    status: 'ACTIVE' | 'STOPPED' | 'ERROR';
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * BotStatusToggleResponse
 */
export type BotStatusToggleResponse = {
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * BotUpdate
 */
export type BotUpdate = {
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Avatar Name
     */
    avatar_name?: string | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm System Prompt
     */
    llm_system_prompt?: string | null;
};

/**
 * BotUpdateResponse
 */
export type BotUpdateResponse = {
    bot: BotRead;
    /**
     * Warning
     */
    warning?: string | null;
};

/**
 * Configs
 */
export type Configs = {
    /**
     * Max Chat History
     */
    max_chat_history: number;
    /**
     * Max Tokens Per Diff
     */
    max_tokens_per_diff: number;
    /**
     * Max Tokens Per Context
     */
    max_tokens_per_context: number;
    /**
     * Default Llm Model
     */
    default_llm_model: string;
    /**
     * Avatar Default Name
     */
    avatar_default_name: string;
    /**
     * Available Llms
     */
    available_llms?: {
        [key: string]: LlmModelInfo;
    };
};

/**
 * ConfigsUpdate
 */
export type ConfigsUpdate = {
    /**
     * Max Chat History
     */
    max_chat_history?: number | null;
    /**
     * Max Tokens Per Diff
     */
    max_tokens_per_diff?: number | null;
    /**
     * Max Tokens Per Context
     */
    max_tokens_per_context?: number | null;
    /**
     * Default Llm Model
     */
    default_llm_model?: string | null;
    /**
     * Avatar Default Name
     */
    avatar_default_name?: string | null;
};

/**
 * ErrorResponseModel
 *
 * Standard error response model.
 */
export type ErrorResponseModel = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * GitlabAuthUrl
 */
export type GitlabAuthUrl = {
    /**
     * Url
     */
    url: string;
};

/**
 * GitlabProject
 */
export type GitlabProject = {
    /**
     * Id
     */
    id: number;
    /**
     * Name With Namespace
     */
    name_with_namespace: string;
    /**
     * Path With Namespace
     */
    path_with_namespace: string;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Access Level
     */
    access_level: number;
    /**
     * Bot Id
     */
    bot_id?: number | null;
    /**
     * Bot Name
     */
    bot_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * GitlabSettingsOut
 */
export type GitlabSettingsOut = {
    /**
     * Gitlab Base
     */
    gitlab_base: string | null;
    /**
     * Gitlab Client Id
     */
    gitlab_client_id: string | null;
    /**
     * Gitlab Client Secret Set
     */
    gitlab_client_secret_set: boolean;
    /**
     * Gitlab Webhook Ssl Verify
     */
    gitlab_webhook_ssl_verify: boolean;
};

/**
 * GitlabSettingsUpdate
 */
export type GitlabSettingsUpdate = {
    /**
     * Gitlab Base
     */
    gitlab_base?: string | null;
    /**
     * Gitlab Client Id
     */
    gitlab_client_id?: string | null;
    /**
     * Gitlab Client Secret
     */
    gitlab_client_secret?: string | null;
    /**
     * Gitlab Webhook Ssl Verify
     */
    gitlab_webhook_ssl_verify?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LLMModelInfo
 */
export type LlmModelInfo = {
    /**
     * Model Name
     */
    model_name: string;
    /**
     * Context Window
     */
    context_window: number;
    /**
     * Max Output Tokens
     */
    max_output_tokens: number;
    /**
     * Temperature
     */
    temperature: number;
    /**
     * Additional Kwargs Schema
     */
    additional_kwargs_schema?: {
        [key: string]: unknown;
    };
};

/**
 * RefreshTokenIn
 */
export type RefreshTokenIn = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RefreshTokenOut
 */
export type RefreshTokenOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Expires In
     */
    expires_in: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * UserInfo
 */
export type AppSchemasAuthUserInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string | null;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
};

/**
 * UserInfo
 */
export type AppSchemasGitlabUserInfo = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Web Url
     */
    web_url: string;
};

export type RefreshTokenApiV1AuthRefreshPostData = {
    body: RefreshTokenIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshTokenApiV1AuthRefreshPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type RefreshTokenApiV1AuthRefreshPostError = RefreshTokenApiV1AuthRefreshPostErrors[keyof RefreshTokenApiV1AuthRefreshPostErrors];

export type RefreshTokenApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: RefreshTokenOut;
};

export type RefreshTokenApiV1AuthRefreshPostResponse = RefreshTokenApiV1AuthRefreshPostResponses[keyof RefreshTokenApiV1AuthRefreshPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body: RefreshTokenIn;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type LogoutApiV1AuthLogoutPostError = LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentUserInfoApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetCurrentUserInfoApiV1AuthMeGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetCurrentUserInfoApiV1AuthMeGetError = GetCurrentUserInfoApiV1AuthMeGetErrors[keyof GetCurrentUserInfoApiV1AuthMeGetErrors];

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasAuthUserInfo;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse = GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];

export type GitlabLoginApiV1AuthGitlabLoginGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/gitlab/login';
};

export type GitlabLoginApiV1AuthGitlabLoginGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GitlabLoginApiV1AuthGitlabLoginGetError = GitlabLoginApiV1AuthGitlabLoginGetErrors[keyof GitlabLoginApiV1AuthGitlabLoginGetErrors];

export type GitlabLoginApiV1AuthGitlabLoginGetResponses = {
    /**
     * Successful Response
     */
    200: GitlabAuthUrl;
};

export type GitlabLoginApiV1AuthGitlabLoginGetResponse = GitlabLoginApiV1AuthGitlabLoginGetResponses[keyof GitlabLoginApiV1AuthGitlabLoginGetResponses];

export type GitlabAuthApiV1AuthGitlabCallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: '/api/v1/auth/gitlab/callback';
};

export type GitlabAuthApiV1AuthGitlabCallbackGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GitlabAuthApiV1AuthGitlabCallbackGetError = GitlabAuthApiV1AuthGitlabCallbackGetErrors[keyof GitlabAuthApiV1AuthGitlabCallbackGetErrors];

export type GitlabAuthApiV1AuthGitlabCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAccessTokenApiV1AuthTokenSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/auth/token/{session_id}';
};

export type GetAccessTokenApiV1AuthTokenSessionIdGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetAccessTokenApiV1AuthTokenSessionIdGetError = GetAccessTokenApiV1AuthTokenSessionIdGetErrors[keyof GetAccessTokenApiV1AuthTokenSessionIdGetErrors];

export type GetAccessTokenApiV1AuthTokenSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: RefreshTokenOut;
};

export type GetAccessTokenApiV1AuthTokenSessionIdGetResponse = GetAccessTokenApiV1AuthTokenSessionIdGetResponses[keyof GetAccessTokenApiV1AuthTokenSessionIdGetResponses];

export type AdminLoginApiV1AdminLoginPostData = {
    body: AdminLoginIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/login';
};

export type AdminLoginApiV1AdminLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type AdminLoginApiV1AdminLoginPostError = AdminLoginApiV1AdminLoginPostErrors[keyof AdminLoginApiV1AdminLoginPostErrors];

export type AdminLoginApiV1AdminLoginPostResponses = {
    /**
     * Successful Response
     */
    200: AdminTokenOut;
};

export type AdminLoginApiV1AdminLoginPostResponse = AdminLoginApiV1AdminLoginPostResponses[keyof AdminLoginApiV1AdminLoginPostResponses];

export type AdminRefreshApiV1AdminRefreshPostData = {
    body: RefreshTokenIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/refresh';
};

export type AdminRefreshApiV1AdminRefreshPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type AdminRefreshApiV1AdminRefreshPostError = AdminRefreshApiV1AdminRefreshPostErrors[keyof AdminRefreshApiV1AdminRefreshPostErrors];

export type AdminRefreshApiV1AdminRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: AdminTokenOut;
};

export type AdminRefreshApiV1AdminRefreshPostResponse = AdminRefreshApiV1AdminRefreshPostResponses[keyof AdminRefreshApiV1AdminRefreshPostResponses];

export type AdminLogoutApiV1AdminLogoutPostData = {
    body: RefreshTokenIn;
    path?: never;
    query?: never;
    url: '/api/v1/admin/logout';
};

export type AdminLogoutApiV1AdminLogoutPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type AdminLogoutApiV1AdminLogoutPostError = AdminLogoutApiV1AdminLogoutPostErrors[keyof AdminLogoutApiV1AdminLogoutPostErrors];

export type AdminLogoutApiV1AdminLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminMeApiV1AdminMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/me';
};

export type AdminMeApiV1AdminMeGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type AdminMeApiV1AdminMeGetError = AdminMeApiV1AdminMeGetErrors[keyof AdminMeApiV1AdminMeGetErrors];

export type AdminMeApiV1AdminMeGetResponses = {
    /**
     * Successful Response
     */
    200: AdminInfo;
};

export type AdminMeApiV1AdminMeGetResponse = AdminMeApiV1AdminMeGetResponses[keyof AdminMeApiV1AdminMeGetResponses];

export type GetGitlabSettingsApiV1AdminSettingsGitlabGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/settings/gitlab';
};

export type GetGitlabSettingsApiV1AdminSettingsGitlabGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetGitlabSettingsApiV1AdminSettingsGitlabGetError = GetGitlabSettingsApiV1AdminSettingsGitlabGetErrors[keyof GetGitlabSettingsApiV1AdminSettingsGitlabGetErrors];

export type GetGitlabSettingsApiV1AdminSettingsGitlabGetResponses = {
    /**
     * Successful Response
     */
    200: GitlabSettingsOut;
};

export type GetGitlabSettingsApiV1AdminSettingsGitlabGetResponse = GetGitlabSettingsApiV1AdminSettingsGitlabGetResponses[keyof GetGitlabSettingsApiV1AdminSettingsGitlabGetResponses];

export type PatchGitlabSettingsApiV1AdminSettingsGitlabPatchData = {
    body: GitlabSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/settings/gitlab';
};

export type PatchGitlabSettingsApiV1AdminSettingsGitlabPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type PatchGitlabSettingsApiV1AdminSettingsGitlabPatchError = PatchGitlabSettingsApiV1AdminSettingsGitlabPatchErrors[keyof PatchGitlabSettingsApiV1AdminSettingsGitlabPatchErrors];

export type PatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponses = {
    /**
     * Successful Response
     */
    200: GitlabSettingsOut;
};

export type PatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponse = PatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponses[keyof PatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponses];

export type GetGitlabUserinfoApiV1GitlabUserinfoGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/gitlab/userinfo';
};

export type GetGitlabUserinfoApiV1GitlabUserinfoGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetGitlabUserinfoApiV1GitlabUserinfoGetError = GetGitlabUserinfoApiV1GitlabUserinfoGetErrors[keyof GetGitlabUserinfoApiV1GitlabUserinfoGetErrors];

export type GetGitlabUserinfoApiV1GitlabUserinfoGetResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasGitlabUserInfo;
};

export type GetGitlabUserinfoApiV1GitlabUserinfoGetResponse = GetGitlabUserinfoApiV1GitlabUserinfoGetResponses[keyof GetGitlabUserinfoApiV1GitlabUserinfoGetResponses];

export type ListGitlabProjectsApiV1GitlabProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/gitlab/projects';
};

export type ListGitlabProjectsApiV1GitlabProjectsGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ListGitlabProjectsApiV1GitlabProjectsGetError = ListGitlabProjectsApiV1GitlabProjectsGetErrors[keyof ListGitlabProjectsApiV1GitlabProjectsGetErrors];

export type ListGitlabProjectsApiV1GitlabProjectsGetResponses = {
    /**
     * Response List Gitlab Projects Api V1 Gitlab Projects Get
     *
     * Successful Response
     */
    200: Array<GitlabProject>;
};

export type ListGitlabProjectsApiV1GitlabProjectsGetResponse = ListGitlabProjectsApiV1GitlabProjectsGetResponses[keyof ListGitlabProjectsApiV1GitlabProjectsGetResponses];

export type ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string | number;
    };
    query?: never;
    url: '/api/v1/gitlab/projects/{project_id}/access-tokens';
};

export type ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetError = ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetErrors[keyof ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetErrors];

export type ListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string | number;
    };
    query?: never;
    url: '/api/v1/gitlab/projects/{project_id}/access-tokens';
};

export type CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostError = CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostErrors[keyof CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostErrors];

export type CreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string | number;
        /**
         * Access Token Id
         */
        access_token_id: string | number;
    };
    query?: never;
    url: '/api/v1/gitlab/projects/{project_id}/access-tokens/{access_token_id}';
};

export type GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetError = GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetErrors[keyof GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetErrors];

export type GetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string | number;
    };
    query?: never;
    url: '/api/v1/gitlab/projects/{project_id}/webhooks';
};

export type ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetError = ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetErrors[keyof ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetErrors];

export type ListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string | number;
    };
    query?: never;
    url: '/api/v1/gitlab/projects/{project_id}/webhooks';
};

export type CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostError = CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostErrors[keyof CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostErrors];

export type CreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string | number;
        /**
         * Hook Id
         */
        hook_id: string | number;
    };
    query?: never;
    url: '/api/v1/gitlab/projects/{project_id}/webhooks/{hook_id}';
};

export type DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteError = DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteErrors[keyof DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteErrors];

export type DeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string | number;
        /**
         * Hook Id
         */
        hook_id: string | number;
    };
    query?: never;
    url: '/api/v1/gitlab/projects/{project_id}/webhooks/{hook_id}';
};

export type GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetError = GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetErrors[keyof GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetErrors];

export type GetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBotStatusApiV1BotsBotIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: '/api/v1/bots/{bot_id}/status';
};

export type GetBotStatusApiV1BotsBotIdStatusGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetBotStatusApiV1BotsBotIdStatusGetError = GetBotStatusApiV1BotsBotIdStatusGetErrors[keyof GetBotStatusApiV1BotsBotIdStatusGetErrors];

export type GetBotStatusApiV1BotsBotIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: BotStatusResponse;
};

export type GetBotStatusApiV1BotsBotIdStatusGetResponse = GetBotStatusApiV1BotsBotIdStatusGetResponses[keyof GetBotStatusApiV1BotsBotIdStatusGetResponses];

export type ListBotsApiV1BotsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/v1/bots/';
};

export type ListBotsApiV1BotsGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ListBotsApiV1BotsGetError = ListBotsApiV1BotsGetErrors[keyof ListBotsApiV1BotsGetErrors];

export type ListBotsApiV1BotsGetResponses = {
    /**
     * Successful Response
     */
    200: BotReadList;
};

export type ListBotsApiV1BotsGetResponse = ListBotsApiV1BotsGetResponses[keyof ListBotsApiV1BotsGetResponses];

export type CreateBotApiV1BotsPostData = {
    body: BotCreate;
    path?: never;
    query?: never;
    url: '/api/v1/bots/';
};

export type CreateBotApiV1BotsPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type CreateBotApiV1BotsPostError = CreateBotApiV1BotsPostErrors[keyof CreateBotApiV1BotsPostErrors];

export type CreateBotApiV1BotsPostResponses = {
    /**
     * Successful Response
     */
    201: BotCreateResponse;
};

export type CreateBotApiV1BotsPostResponse = CreateBotApiV1BotsPostResponses[keyof CreateBotApiV1BotsPostResponses];

export type DeleteBotApiV1BotsBotIdDeleteData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: '/api/v1/bots/{bot_id}';
};

export type DeleteBotApiV1BotsBotIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type DeleteBotApiV1BotsBotIdDeleteError = DeleteBotApiV1BotsBotIdDeleteErrors[keyof DeleteBotApiV1BotsBotIdDeleteErrors];

export type DeleteBotApiV1BotsBotIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: BotDeleteResponse;
};

export type DeleteBotApiV1BotsBotIdDeleteResponse = DeleteBotApiV1BotsBotIdDeleteResponses[keyof DeleteBotApiV1BotsBotIdDeleteResponses];

export type GetBotApiV1BotsBotIdGetData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: '/api/v1/bots/{bot_id}';
};

export type GetBotApiV1BotsBotIdGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetBotApiV1BotsBotIdGetError = GetBotApiV1BotsBotIdGetErrors[keyof GetBotApiV1BotsBotIdGetErrors];

export type GetBotApiV1BotsBotIdGetResponses = {
    /**
     * Successful Response
     */
    200: BotRead;
};

export type GetBotApiV1BotsBotIdGetResponse = GetBotApiV1BotsBotIdGetResponses[keyof GetBotApiV1BotsBotIdGetResponses];

export type UpdateBotApiV1BotsBotIdPatchData = {
    body: BotUpdate;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: '/api/v1/bots/{bot_id}';
};

export type UpdateBotApiV1BotsBotIdPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type UpdateBotApiV1BotsBotIdPatchError = UpdateBotApiV1BotsBotIdPatchErrors[keyof UpdateBotApiV1BotsBotIdPatchErrors];

export type UpdateBotApiV1BotsBotIdPatchResponses = {
    /**
     * Successful Response
     */
    200: BotUpdateResponse;
};

export type UpdateBotApiV1BotsBotIdPatchResponse = UpdateBotApiV1BotsBotIdPatchResponses[keyof UpdateBotApiV1BotsBotIdPatchResponses];

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: '/api/v1/bots/{bot_id}/new-access-token';
};

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchError = CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchErrors[keyof CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchErrors];

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponses = {
    /**
     * Successful Response
     */
    200: BotUpdateResponse;
};

export type CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponse = CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponses[keyof CreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponses];

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: '/api/v1/bots/{bot_id}/toggle-active';
};

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchError = ToggleBotActiveApiV1BotsBotIdToggleActivePatchErrors[keyof ToggleBotActiveApiV1BotsBotIdToggleActivePatchErrors];

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponses = {
    /**
     * Successful Response
     */
    200: BotStatusToggleResponse;
};

export type ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponse = ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponses[keyof ToggleBotActiveApiV1BotsBotIdToggleActivePatchResponses];

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: '/api/v1/bots/{bot_id}/revoke';
};

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteError = RevokeBotTokenApiV1BotsBotIdRevokeDeleteErrors[keyof RevokeBotTokenApiV1BotsBotIdRevokeDeleteErrors];

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponse = RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponses[keyof RevokeBotTokenApiV1BotsBotIdRevokeDeleteResponses];

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchData = {
    body?: never;
    path: {
        /**
         * Bot Id
         */
        bot_id: number;
    };
    query?: never;
    url: '/api/v1/bots/{bot_id}/rotate-token';
};

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchError = RotateBotTokenApiV1BotsBotIdRotateTokenPatchErrors[keyof RotateBotTokenApiV1BotsBotIdRotateTokenPatchErrors];

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponses = {
    /**
     * Successful Response
     */
    200: BotRead;
};

export type RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponse = RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponses[keyof RotateBotTokenApiV1BotsBotIdRotateTokenPatchResponses];

export type GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/available-avatars';
};

export type GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetError = GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetErrors[keyof GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetErrors];

export type GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponses = {
    /**
     * Response Get Available Avatars Api V1 Config Available Avatars Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponse = GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponses[keyof GetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponses];

export type GetAvailableLlmsApiV1ConfigAvailableLlmsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/available-llms';
};

export type GetAvailableLlmsApiV1ConfigAvailableLlmsGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetAvailableLlmsApiV1ConfigAvailableLlmsGetError = GetAvailableLlmsApiV1ConfigAvailableLlmsGetErrors[keyof GetAvailableLlmsApiV1ConfigAvailableLlmsGetErrors];

export type GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponses = {
    /**
     * Response Get Available Llms Api V1 Config Available Llms Get
     *
     * Successful Response
     */
    200: {
        [key: string]: LlmModelInfo;
    };
};

export type GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponse = GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponses[keyof GetAvailableLlmsApiV1ConfigAvailableLlmsGetResponses];

export type AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostData = {
    body: LlmModelInfo;
    path?: never;
    query?: never;
    url: '/api/v1/config/available-llms';
};

export type AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostError = AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostErrors[keyof AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostErrors];

export type AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostResponses = {
    /**
     * Successful Response
     */
    200: LlmModelInfo;
};

export type AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostResponse = AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostResponses[keyof AddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostResponses];

export type DeleteAvailableLlmApiV1ConfigAvailableLlmsModelNameDeleteData = {
    body?: never;
    path: {
        /**
         * Model Name
         */
        model_name: string;
    };
    query?: never;
    url: '/api/v1/config/available-llms/{model_name}';
};

export type DeleteAvailableLlmApiV1ConfigAvailableLlmsModelNameDeleteErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type DeleteAvailableLlmApiV1ConfigAvailableLlmsModelNameDeleteError = DeleteAvailableLlmApiV1ConfigAvailableLlmsModelNameDeleteErrors[keyof DeleteAvailableLlmApiV1ConfigAvailableLlmsModelNameDeleteErrors];

export type DeleteAvailableLlmApiV1ConfigAvailableLlmsModelNameDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetConfigsApiV1ConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/';
};

export type GetConfigsApiV1ConfigGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetConfigsApiV1ConfigGetError = GetConfigsApiV1ConfigGetErrors[keyof GetConfigsApiV1ConfigGetErrors];

export type GetConfigsApiV1ConfigGetResponses = {
    /**
     * Successful Response
     */
    200: Configs;
};

export type GetConfigsApiV1ConfigGetResponse = GetConfigsApiV1ConfigGetResponses[keyof GetConfigsApiV1ConfigGetResponses];

export type UpdateConfigsApiV1ConfigPatchData = {
    body: ConfigsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/config/';
};

export type UpdateConfigsApiV1ConfigPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type UpdateConfigsApiV1ConfigPatchError = UpdateConfigsApiV1ConfigPatchErrors[keyof UpdateConfigsApiV1ConfigPatchErrors];

export type UpdateConfigsApiV1ConfigPatchResponses = {
    /**
     * Successful Response
     */
    200: Configs;
};

export type UpdateConfigsApiV1ConfigPatchResponse = UpdateConfigsApiV1ConfigPatchResponses[keyof UpdateConfigsApiV1ConfigPatchResponses];

export type WebhookApiV1WebhooksBotUserIdPostData = {
    body?: never;
    path: {
        /**
         * Bot User Id
         */
        bot_user_id: number;
    };
    query?: never;
    url: '/api/v1/webhooks/{bot_user_id}';
};

export type WebhookApiV1WebhooksBotUserIdPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Forbidden
     */
    403: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type WebhookApiV1WebhooksBotUserIdPostError = WebhookApiV1WebhooksBotUserIdPostErrors[keyof WebhookApiV1WebhooksBotUserIdPostErrors];

export type WebhookApiV1WebhooksBotUserIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
