// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * GitlabAuthUrl
 */
export const zGitlabAuthUrl = z.object({
    url: z.string(),
});

/**
 * RefreshTokenIn
 */
export const zRefreshTokenIn = z.object({
    refresh_token: z.string(),
});

/**
 * RefreshTokenOut
 */
export const zRefreshTokenOut = z.object({
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.optional(z.string()).default("Bearer"),
    expires_in: z.int(),
});

/**
 * UserInfo
 */
export const zUserInfo = z.object({
    id: z.int(),
    email: z.string(),
    username: z.union([z.string(), z.null()]),
    avatar_url: z.union([z.string(), z.null()]),
    is_active: z.boolean(),
    is_superuser: z.boolean(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError)),
});

export const zRefreshTokenApiV1AuthRefreshPostData = z.object({
    body: zRefreshTokenIn,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRefreshTokenApiV1AuthRefreshPostResponse = zRefreshTokenOut;

export const zLogoutApiV1AuthLogoutPostData = z.object({
    body: zRefreshTokenIn,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

export const zGetCurrentUserInfoApiV1AuthMeGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetCurrentUserInfoApiV1AuthMeGetResponse = zUserInfo;

export const zGitlabLoginApiV1AuthGitlabLoginGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGitlabLoginApiV1AuthGitlabLoginGetResponse = zGitlabAuthUrl;

export const zGitlabAuthApiV1AuthGitlabCallbackGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        code: z.string(),
        state: z.string(),
    }),
});

/**
 * Successful Response
 */
export const zGitlabAuthApiV1AuthGitlabCallbackGetResponse = zRefreshTokenOut;

export const zGetGitlabUserinfoApiV1GitlabUserinfoGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

export const zGetGitlabProjectsApiV1GitlabProjectsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});
