// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * AdminInfo
 */
export const zAdminInfo = z.object({
    id: z.int(),
    email: z.string(),
    username: z.union([
        z.string(),
        z.null()
    ]),
    is_superuser: z.boolean()
});

/**
 * AdminLoginIn
 */
export const zAdminLoginIn = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * AdminTokenOut
 */
export const zAdminTokenOut = z.object({
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.optional(z.string()).default('Bearer'),
    expires_in: z.int()
});

/**
 * BotCreate
 */
export const zBotCreate = z.object({
    name: z.string(),
    gitlab_project_path: z.string()
});

/**
 * BotDeleteResponse
 */
export const zBotDeleteResponse = z.object({
    warning: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * BotRead
 */
export const zBotRead = z.object({
    id: z.int(),
    is_active: z.boolean(),
    gitlab_project_path: z.string(),
    gitlab_access_token_id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    gitlab_user_id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    gitlab_user_name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    gitlab_webhook_id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    gitlab_webhook_secret: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    avatar_name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    avatar_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    llm_model: z.string(),
    llm_max_output_tokens: z.int(),
    llm_temperature: z.number(),
    llm_system_prompt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    llm_additional_kwargs: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ]))
});

/**
 * BotCreateResponse
 */
export const zBotCreateResponse = z.object({
    bot: zBotRead,
    warning: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * BotReadList
 */
export const zBotReadList = z.object({
    total: z.int(),
    items: z.array(zBotRead)
});

/**
 * BotStatusResponse
 */
export const zBotStatusResponse = z.object({
    status: z.enum([
        'ACTIVE',
        'STOPPED',
        'ERROR'
    ]),
    error_message: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * BotStatusToggleResponse
 */
export const zBotStatusToggleResponse = z.object({
    is_active: z.boolean()
});

/**
 * BotUpdate
 */
export const zBotUpdate = z.object({
    is_active: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    avatar_name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    llm_model: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    llm_system_prompt: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * BotUpdateResponse
 */
export const zBotUpdateResponse = z.object({
    bot: zBotRead,
    warning: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * ConfigsUpdate
 */
export const zConfigsUpdate = z.object({
    max_chat_history: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    max_tokens_per_diff: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    max_tokens_per_context: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    default_llm_model: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    avatar_default_name: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * ErrorResponseModel
 *
 * Standard error response model.
 */
export const zErrorResponseModel = z.object({
    detail: z.string()
});

/**
 * GitlabAuthUrl
 */
export const zGitlabAuthUrl = z.object({
    url: z.string()
});

/**
 * GitlabProject
 */
export const zGitlabProject = z.object({
    id: z.int(),
    name_with_namespace: z.string(),
    path_with_namespace: z.string(),
    web_url: z.string(),
    access_level: z.int(),
    bot_id: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    bot_name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    avatar_url: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * GitlabSettingsOut
 */
export const zGitlabSettingsOut = z.object({
    gitlab_base: z.union([
        z.string(),
        z.null()
    ]),
    gitlab_client_id: z.union([
        z.string(),
        z.null()
    ]),
    gitlab_client_secret_set: z.boolean(),
    gitlab_webhook_ssl_verify: z.boolean()
});

/**
 * GitlabSettingsUpdate
 */
export const zGitlabSettingsUpdate = z.object({
    gitlab_base: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    gitlab_client_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    gitlab_client_secret: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    gitlab_webhook_ssl_verify: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

/**
 * LLMModelInfo
 */
export const zLlmModelInfo = z.object({
    model_name: z.string(),
    context_window: z.int(),
    max_output_tokens: z.int(),
    temperature: z.number(),
    additional_kwargs_schema: z.optional(z.record(z.string(), z.unknown()))
});

/**
 * Configs
 */
export const zConfigs = z.object({
    max_chat_history: z.int(),
    max_tokens_per_diff: z.int(),
    max_tokens_per_context: z.int(),
    default_llm_model: z.string(),
    avatar_default_name: z.string(),
    available_llms: z.optional(z.record(z.string(), zLlmModelInfo))
});

/**
 * RefreshTokenIn
 */
export const zRefreshTokenIn = z.object({
    refresh_token: z.string()
});

/**
 * RefreshTokenOut
 */
export const zRefreshTokenOut = z.object({
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.optional(z.string()).default('Bearer'),
    expires_in: z.int()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([
        z.string(),
        z.int()
    ])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

/**
 * UserInfo
 */
export const zAppSchemasAuthUserInfo = z.object({
    id: z.int(),
    email: z.string(),
    username: z.union([
        z.string(),
        z.null()
    ]),
    avatar_url: z.union([
        z.string(),
        z.null()
    ]),
    is_active: z.boolean(),
    is_superuser: z.boolean()
});

/**
 * UserInfo
 */
export const zAppSchemasGitlabUserInfo = z.object({
    username: z.string(),
    email: z.string(),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    avatar_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    web_url: z.string()
});

export const zRefreshTokenApiV1AuthRefreshPostData = z.object({
    body: zRefreshTokenIn,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zRefreshTokenApiV1AuthRefreshPostResponse = zRefreshTokenOut;

export const zLogoutApiV1AuthLogoutPostData = z.object({
    body: zRefreshTokenIn,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetCurrentUserInfoApiV1AuthMeGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetCurrentUserInfoApiV1AuthMeGetResponse = zAppSchemasAuthUserInfo;

export const zGitlabLoginApiV1AuthGitlabLoginGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGitlabLoginApiV1AuthGitlabLoginGetResponse = zGitlabAuthUrl;

export const zGitlabAuthApiV1AuthGitlabCallbackGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        code: z.string(),
        state: z.string()
    })
});

export const zGetAccessTokenApiV1AuthTokenSessionIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        session_id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetAccessTokenApiV1AuthTokenSessionIdGetResponse = zRefreshTokenOut;

export const zAdminLoginApiV1AdminLoginPostData = z.object({
    body: zAdminLoginIn,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAdminLoginApiV1AdminLoginPostResponse = zAdminTokenOut;

export const zAdminRefreshApiV1AdminRefreshPostData = z.object({
    body: zRefreshTokenIn,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAdminRefreshApiV1AdminRefreshPostResponse = zAdminTokenOut;

export const zAdminLogoutApiV1AdminLogoutPostData = z.object({
    body: zRefreshTokenIn,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAdminMeApiV1AdminMeGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAdminMeApiV1AdminMeGetResponse = zAdminInfo;

export const zGetGitlabSettingsApiV1AdminSettingsGitlabGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetGitlabSettingsApiV1AdminSettingsGitlabGetResponse = zGitlabSettingsOut;

export const zPatchGitlabSettingsApiV1AdminSettingsGitlabPatchData = z.object({
    body: zGitlabSettingsUpdate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zPatchGitlabSettingsApiV1AdminSettingsGitlabPatchResponse = zGitlabSettingsOut;

export const zGetGitlabUserinfoApiV1GitlabUserinfoGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetGitlabUserinfoApiV1GitlabUserinfoGetResponse = zAppSchemasGitlabUserInfo;

export const zListGitlabProjectsApiV1GitlabProjectsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        per_page: z.optional(z.int().gte(1).lte(100)).default(20),
        search: z.optional(z.union([
            z.string().max(100),
            z.null()
        ]))
    }))
});

/**
 * Response List Gitlab Projects Api V1 Gitlab Projects Get
 *
 * Successful Response
 */
export const zListGitlabProjectsApiV1GitlabProjectsGetResponse = z.array(zGitlabProject);

export const zListGitlabProjectAccessTokensApiV1GitlabProjectsProjectIdAccessTokensGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        project_id: z.union([
            z.string(),
            z.int()
        ])
    }),
    query: z.optional(z.never())
});

export const zCreateGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensPostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        project_id: z.union([
            z.string(),
            z.int()
        ])
    }),
    query: z.optional(z.never())
});

export const zGetGitlabProjectAccessTokenApiV1GitlabProjectsProjectIdAccessTokensAccessTokenIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        project_id: z.union([
            z.string(),
            z.int()
        ]),
        access_token_id: z.union([
            z.string(),
            z.int()
        ])
    }),
    query: z.optional(z.never())
});

export const zListGitlabProjectWebhooksApiV1GitlabProjectsProjectIdWebhooksGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        project_id: z.union([
            z.string(),
            z.int()
        ])
    }),
    query: z.optional(z.never())
});

export const zCreateGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksPostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        project_id: z.union([
            z.string(),
            z.int()
        ])
    }),
    query: z.optional(z.never())
});

export const zDeleteGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        project_id: z.union([
            z.string(),
            z.int()
        ]),
        hook_id: z.union([
            z.string(),
            z.int()
        ])
    }),
    query: z.optional(z.never())
});

export const zGetGitlabProjectWebhookApiV1GitlabProjectsProjectIdWebhooksHookIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        project_id: z.union([
            z.string(),
            z.int()
        ]),
        hook_id: z.union([
            z.string(),
            z.int()
        ])
    }),
    query: z.optional(z.never())
});

export const zGetBotStatusApiV1BotsBotIdStatusGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bot_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetBotStatusApiV1BotsBotIdStatusGetResponse = zBotStatusResponse;

export const zListBotsApiV1BotsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int()).default(1),
        per_page: z.optional(z.int()).default(20)
    }))
});

/**
 * Successful Response
 */
export const zListBotsApiV1BotsGetResponse = zBotReadList;

export const zCreateBotApiV1BotsPostData = z.object({
    body: zBotCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zCreateBotApiV1BotsPostResponse = zBotCreateResponse;

export const zDeleteBotApiV1BotsBotIdDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bot_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDeleteBotApiV1BotsBotIdDeleteResponse = zBotDeleteResponse;

export const zGetBotApiV1BotsBotIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bot_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetBotApiV1BotsBotIdGetResponse = zBotRead;

export const zUpdateBotApiV1BotsBotIdPatchData = z.object({
    body: zBotUpdate,
    path: z.object({
        bot_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zUpdateBotApiV1BotsBotIdPatchResponse = zBotUpdateResponse;

export const zCreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bot_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zCreateNewBotAccessTokenApiV1BotsBotIdNewAccessTokenPatchResponse = zBotUpdateResponse;

export const zToggleBotActiveApiV1BotsBotIdToggleActivePatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bot_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zToggleBotActiveApiV1BotsBotIdToggleActivePatchResponse = zBotStatusToggleResponse;

export const zRevokeBotTokenApiV1BotsBotIdRevokeDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bot_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zRevokeBotTokenApiV1BotsBotIdRevokeDeleteResponse = z.void();

export const zRotateBotTokenApiV1BotsBotIdRotateTokenPatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bot_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zRotateBotTokenApiV1BotsBotIdRotateTokenPatchResponse = zBotRead;

export const zGetAvailableAvatarsApiV1ConfigAvailableAvatarsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get Available Avatars Api V1 Config Available Avatars Get
 *
 * Successful Response
 */
export const zGetAvailableAvatarsApiV1ConfigAvailableAvatarsGetResponse = z.record(z.string(), z.string());

export const zGetAvailableLlmsApiV1ConfigAvailableLlmsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get Available Llms Api V1 Config Available Llms Get
 *
 * Successful Response
 */
export const zGetAvailableLlmsApiV1ConfigAvailableLlmsGetResponse = z.record(z.string(), zLlmModelInfo);

export const zAddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostData = z.object({
    body: zLlmModelInfo,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAddUpdateAvailableLlmApiV1ConfigAvailableLlmsPostResponse = zLlmModelInfo;

export const zDeleteAvailableLlmApiV1ConfigAvailableLlmsModelNameDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        model_name: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetConfigsApiV1ConfigGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetConfigsApiV1ConfigGetResponse = zConfigs;

export const zUpdateConfigsApiV1ConfigPatchData = z.object({
    body: zConfigsUpdate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zUpdateConfigsApiV1ConfigPatchResponse = zConfigs;

export const zWebhookApiV1WebhooksBotUserIdPostData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        bot_user_id: z.int()
    }),
    query: z.optional(z.never())
});
